### ISSUE TITLE
Update on IP change only

### ISSUE THREAD

**Issue by SinaBina** [drittich/CloudflareDynDNS#49]
Hi
Is it possible to update DNS records only if the host IP has been changed?
Currently we get somehow unnecessary update every N minutes while it may be more efficient to update only if it is changed.

Thanks

**Comment by drittich** [comment]
How are you determining that it's updating the DNS record?

**Comment by drittich** [comment]
I took a look at the code and you are correct. I recall making this decision to update Cloudflare each time because of the potential that the DNS entries had been updated through the Cloudflare UI or some other DNS tool. Because this situation is expected to be rare I am changing the behaviour to only do the update when the public IP address changes. 

If it turns out some users prefer it to update the Cloudflare DNS entries each time, I will add an option in Settings for this. This change will go out with the next release.

Fixed in commit https://github.com/drittich/DnsTube/commit/365f4469626feef53c36a7a42678011a7c8ee626
